services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=store'
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - './volumes/code/postgres:/var/lib/postgresql/data'