logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    al.imcode.ec: INFO

spring:
  application:
    name: ec
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: admin
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: ecommerce_v1
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: ecommerce_v1
    contexts: dev
  #    drop-first: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

